# cp: nixfleet control plane.
#
# Polls forge's git for fleet.resolved.json + signature. Validates against
# the ed25519 pubkey declared in modules/trust.nix. Dispatches rollout actions
# to agents per channel/wave/edge policies declared in fleet.nix.
#
# Compliance: NIS2 essential (the demo's compliance posture demonstration).
#
# This file returns the `nixosArgs` attrset for cp (RFC-0011 §2.2 +
# 9e operator path). The framework's `mkFleet` wrapper in
# `lib/default.nix` calls `mkHost` per host with `hostName`,
# `platform`, and `fleetResolved` pre-bound from
# `mkFleet { hosts.cp.system = "..."; ... }` in fleet.nix.
# Operators consume the built config at `self.fleet.nixosConfigurations.cp`.
{inputs, ...}: {
  isVm = true;
  hostSpec = {
    userName = "root";
    timeZone = "UTC";
    locale = "en_US.UTF-8";
    vmPortForwards = {
      "8443" = 8443; # control plane TLS
    };
    # Compliance probes + reconciler state are tighter than the 1024 default.
    vmRam = 2048;
  };
  modules = [
    ./_shared/qemu-vm.nix
    ../modules/trust.nix

    ../modules/fleet-version.nix

    ../modules/use-forge-cache.nix
    inputs.nixfleet.scopes.persistence.impermanence
    inputs.compliance.nixosModules.nis2
    (
      {pkgs, ...}: {
        services.nixfleet-control-plane = {
          enable = true;
          listen = "0.0.0.0:8443";
          openFirewall = true;

          # Agent cert CN suffix. Demo CA has no dNSName constraint
          # so any string works; production fleets must match this to
          # the issuance CA's dNSName extension (nixfleet D14).
          agentCnSuffix = "fleet.demo";

          tls.cert = "/var/lib/nixfleet-control-plane/tls/cert.pem";
          tls.key = "/var/lib/nixfleet-control-plane/tls/key.pem";
          # mTLS client verification: same fleet CA that signs agents
          # also signs operator certs. Without this, CP starts in
          # "TLS-only" mode and returns 401 for every /v1/* call.
          tls.clientCa = "/etc/nixfleet-demo/fleet-ca.pem";

          # Issuance CA: signs agent client certs at /v1/enroll and
          # /v1/agent/renew. Demo: file-based (FileCaSigner). Production:
          # tpmCaPubkeyRaw + tpmCaSignWrapper - keeps the CA private
          # half inside the TPM and survives disk loss.
          fleetCaCert = "/etc/nixfleet-demo/fleet-ca.pem";
          fleetCaKey = "/etc/nixfleet-demo/fleet-ca-key.pem";

          # Poll forge's Forgejo HTTP. Inter-VM hostname resolution is
          # via the multicast VLAN configured by `start-vm --vlan 1234`
          # + the static-IP/extraHosts wiring in modules/vm-network.nix.
          channelRefsSource = {
            artifactUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/fleet.resolved.json";
            signatureUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/fleet.resolved.json.sig";
          };

          # Empty list is a steady state for the demo. CP still verifies the
          # (empty) signed revocations artifact - exercises gap C.
          revocationsSource = {
            artifactUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/revocations.json";
            signatureUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/revocations.json.sig";
          };

          # Signed bootstrap-nonce allowlist (nixfleet#96). CP refuses
          # /v1/enroll for any nonce not in this signed list. The file
          # is produced by CI from fleet.bootstrapNonces in fleet.nix.
          bootstrapNoncesSource = {
            artifactUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/bootstrap-nonces.json";
            signatureUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/bootstrap-nonces.json.sig";
          };

          # Per-rollout manifest source. nixfleet-release writes
          # releases/rollouts/<rolloutId>.json{,.sig} for each rollout;
          # CP substitutes {rolloutId} in the template and serves the
          # signed manifest at /v1/rollouts/<id> to its agents. Without
          # this, agents enroll successfully but block forever on
          # "rollout manifest gate failed" because /v1/rollouts/* 503s.
          rolloutsSource = {
            artifactUrlTemplate = "http://forge:3001/demo/fleet/raw/branch/main/releases/rollouts/{rolloutId}.json";
            signatureUrlTemplate = "http://forge:3001/demo/fleet/raw/branch/main/releases/rollouts/{rolloutId}.json.sig";
          };
        };

        # Fleet CA: pre-generated by secrets/regenerate-demo-identity.sh.
        # The cert half is also installed on agents at the same path
        # (web-01, web-02) as `tls.caCert` - agents use it to verify CP's
        # TLS server cert (which CP signs with this CA at first boot).
        environment.etc."nixfleet-demo/fleet-ca.pem" = {
          text = builtins.readFile ../secrets/fleet-ca.pem;
          mode = "0644";
        };
        environment.etc."nixfleet-demo/fleet-ca-key.pem" = {
          text = builtins.readFile ../secrets/fleet-ca-key.pem;
          mode = "0600";
        };

        # cp also runs the agent and reports to itself. Same wiring as
        # web hosts -- the agent talks to https://cp:8443 (loopback via
        # the VLAN address), authenticates with its own mTLS client cert,
        # and applies new closures when fleet.nix declares cp on a newer
        # ref. Brief /v1/* outage during self-rollout is acceptable: web
        # agents retry, and CP comes back up within one poll cycle.
        services.nixfleet-agent = {
          enable = true;
          controlPlaneUrl = "https://cp:8443";
          tags = ["infra"];
          tls.caCert = "/var/lib/nixfleet-demo/fleet-ca.pem";
          tls.clientKey = "/var/lib/nixfleet-demo/agent-client.key";
          bootstrapTokenFile = "/var/lib/nixfleet-demo/bootstrap-token.json";
        };

        # Gate the agent on its private key (same pattern as the web hosts).
        # Without this, the unit crash-loops until provision-secrets stages
        # the key and starts it explicitly.
        systemd.services.nixfleet-agent.unitConfig.ConditionPathExists = "/var/lib/nixfleet-demo/agent-client.key";

        # /var/lib/nixfleet must exist before the agent's first-run
        # atomic-write of agent-cert.pem.
        systemd.tmpfiles.rules = [
          "d /var/lib/nixfleet 0700 root root - -"
        ];

        # Gate both the TLS keygen oneshot and the control-plane service
        # on the fleet CA key existing. Without provisioning, the daemon
        # stays inert (no crash-loop logging "file not found" every second).
        # `nix run .#provision-secrets -- -h cp` lands the file and then
        # starts the units explicitly.
        systemd.services.nixfleet-control-plane.unitConfig.ConditionPathExists = "/var/lib/nixfleet-demo/fleet-ca-key.pem";

        # First-boot oneshot: sign the CP TLS server cert using the
        # pre-installed fleet CA. The agent's `tls.caCert` is the same
        # CA cert, so the chain validates without out-of-band trust
        # bootstrap. SAN list: `cp` + `cp.demo.invalid` for VLAN peers,
        # 127.0.0.1 + 10.0.100.1 for local probes and the host
        # port-forward (mkVmApps maps 8443 -> guest:8443).
        systemd.services.nixfleet-cp-tls-keygen = {
          description = "First-boot CP TLS server cert (signed by fleet CA)";
          wantedBy = ["multi-user.target"];
          before = ["nixfleet-control-plane.service"];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            User = "root";
            UMask = "0027";
          };
          script = ''
            set -euo pipefail
            tls_dir=/var/lib/nixfleet-control-plane/tls
            mkdir -p "$tls_dir"
            cert="$tls_dir/cert.pem"
            key="$tls_dir/key.pem"
            csr="$tls_dir/cp.csr"
            if [ -f "$cert" ] && [ -f "$key" ]; then
              exit 0
            fi
            ${pkgs.openssl}/bin/openssl genpkey -algorithm ed25519 -out "$key"
            chmod 0600 "$key"
            ${pkgs.openssl}/bin/openssl req -new -key "$key" -out "$csr" \
              -subj "/CN=cp.demo.invalid"
            cat > "$tls_dir/cp.ext" <<EOF
            subjectAltName=DNS:cp,DNS:cp.demo.invalid,DNS:localhost,IP:127.0.0.1,IP:10.0.100.1
            extendedKeyUsage=serverAuth
            EOF
            ${pkgs.openssl}/bin/openssl x509 -req \
              -in "$csr" \
              -CA /etc/nixfleet-demo/fleet-ca.pem \
              -CAkey /etc/nixfleet-demo/fleet-ca-key.pem \
              -CAcreateserial \
              -out "$cert" \
              -days 3650 \
              -extfile "$tls_dir/cp.ext"
            chmod 0644 "$cert"
            rm -f "$csr" "$tls_dir/cp.ext"
          '';
        };

        compliance.frameworks.nis2 = {
          enable = true;
          entityType = "essential";
        };
        compliance.governance.hostType = "server";

        # Operator surface on cp: nixfleet CLI, jq for poking at JSON,
        # git for editing fleet.nix and pushing to forge in the recording
        # / pilot workflow. Without git, demoing the signed-GitOps loop
        # from cp requires shelling out via `nix shell nixpkgs#git` --
        # bake it in instead.
        environment.systemPackages = [
          inputs.nixfleet.packages.x86_64-linux.nixfleet-cli
          pkgs.jq
          pkgs.git
        ];

        # Operator CLI defaults. `nixfleet status` reads these from the
        # environment so the operator doesn't have to type --cp-url,
        # --ca-cert, --client-cert, --client-key on every invocation.
        # `operator.pem` + `operator.key` are scp'd by provision-secrets;
        # the matching CA is what CP itself uses for client verification.
        environment.variables = {
          NIXFLEET_CP_URL = "https://cp:8443";
          NIXFLEET_CA_CERT = "/etc/nixfleet-demo/fleet-ca.pem";
          NIXFLEET_CLIENT_CERT = "/var/lib/nixfleet-demo/operator.pem";
          NIXFLEET_CLIENT_KEY = "/var/lib/nixfleet-demo/operator.key";
        };

        # SSH config for `forge` so `git push forge HEAD:main` resolves
        # the right port, user, and identity without any per-call
        # GIT_SSH_COMMAND or in-repo remote tweaking. The identity file
        # is staged by `provision-secrets` into /var/lib/nixfleet-demo/
        # (demo-ssh-key, mode 0600) so it survives reboots via the
        # persistence directories below.
        programs.ssh.extraConfig = ''
          Host forge
            Port 222
            User git
            IdentityFile /var/lib/nixfleet-demo/demo-ssh-key
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            LogLevel ERROR
        '';

        # /var/lib/nixfleet-demo persists the operator-provisioned
        # private material across reboots (impermanence wipes /).
        nixfleet.persistence.directories = [
          "/var/lib/nixfleet-control-plane"
          "/var/lib/nixfleet-compliance"
        ];
      }
    )
  ];
}
