# cp: nixfleet control plane.
#
# Polls forge's git for fleet.resolved.json + signature. Validates against
# the ed25519 pubkey declared in modules/trust.nix. Dispatches rollout actions
# to agents per channel/wave/edge policies declared in fleet.nix.
#
# Compliance: NIS2 essential (the demo's compliance posture demonstration).
{inputs, ...}:
inputs.nixfleet.lib.mkHost {
  hostName = "cp";
  platform = "x86_64-linux";
  isVm = true;
  hostSpec = {
    userName = "root";
    timeZone = "UTC";
    locale = "en_US.UTF-8";
    vmPortForwards = {
      "8443" = 8443; # control plane TLS
    };
    # Compliance probes + reconciler state are tighter than the 1024 default.
    vmRam = 2048;
  };
  modules = [
    ./_shared/qemu-vm.nix
    ../modules/trust.nix
    inputs.nixfleet.scopes.persistence.impermanence
    inputs.compliance.nixosModules.nis2
    (
      {pkgs, ...}: {
        services.nixfleet-control-plane = {
          enable = true;
          listen = "0.0.0.0:8443";
          openFirewall = true;
          tls.cert = "/var/lib/nixfleet-control-plane/tls/cert.pem";
          tls.key = "/var/lib/nixfleet-control-plane/tls/key.pem";

          # Issuance CA: signs agent client certs at /v1/enroll and
          # /v1/agent/renew. Demo: file-based (FileCaSigner). Production:
          # tpmCaPubkeyRaw + tpmCaSignWrapper — keeps the CA private
          # half inside the TPM and survives disk loss.
          fleetCaCert = "/etc/nixfleet-demo/fleet-ca.pem";
          fleetCaKey = "/etc/nixfleet-demo/fleet-ca-key.pem";

          # Poll forge's Forgejo HTTP. Inter-VM hostname resolution is
          # via the multicast VLAN configured by `start-vm --vlan 1234`
          # + the static-IP/extraHosts wiring in modules/vm-network.nix.
          channelRefsSource = {
            artifactUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/fleet.resolved.json";
            signatureUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/fleet.resolved.json.sig";
          };

          # Empty list is a steady state for the demo. CP still verifies the
          # (empty) signed revocations artifact — exercises gap C.
          revocationsSource = {
            artifactUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/revocations.json";
            signatureUrl = "http://forge:3001/demo/fleet/raw/branch/main/releases/revocations.json.sig";
          };
        };

        # Fleet CA: pre-generated by secrets/regenerate-demo-identity.sh.
        # The cert half is also installed on agents at the same path
        # (web-01, web-02) as `tls.caCert` — agents use it to verify CP's
        # TLS server cert (which CP signs with this CA at first boot).
        environment.etc."nixfleet-demo/fleet-ca.pem" = {
          text = builtins.readFile ../secrets/fleet-ca.pem;
          mode = "0644";
        };
        environment.etc."nixfleet-demo/fleet-ca-key.pem" = {
          text = builtins.readFile ../secrets/fleet-ca-key.pem;
          mode = "0600";
        };

        # Operator mTLS cert (clientAuth EKU, CN=operator-demo@nixfleet-demo-cp,
        # signed by the fleet CA). Required by `nixfleet status` post-v0.2:
        # the CLI authenticates as an operator via mTLS, not via shell uid.
        # Demo: cert is checked into secrets/ and installed here for "ssh
        # into cp → nixfleet status" to Just Work without `nixfleet config
        # init`. Production: each operator mints their own via
        # `nixfleet mint-operator-cert` against the offline fleet root.
        environment.etc."nixfleet-demo/operator.pem" = {
          text = builtins.readFile ../secrets/operator.pem;
          mode = "0644";
        };
        environment.etc."nixfleet-demo/operator.key" = {
          text = builtins.readFile ../secrets/operator.key;
          mode = "0600";
        };

        # Set NIXFLEET_* env vars so the CLI resolves its mTLS config
        # without needing `nixfleet config init` or a `~/.config/nixfleet/
        # config.toml`. Precedence: flag > NIXFLEET_* env > config file.
        # URL uses `cp` (resolves to 10.0.100.1 via vm-network.nix) — the
        # SAN list also covers `localhost`/`127.0.0.1` for parity with
        # mkVmApps' host port-forward (host:8443 → guest:8443).
        environment.variables = {
          NIXFLEET_CP_URL = "https://cp:8443";
          NIXFLEET_CA_CERT = "/etc/nixfleet-demo/fleet-ca.pem";
          NIXFLEET_CLIENT_CERT = "/etc/nixfleet-demo/operator.pem";
          NIXFLEET_CLIENT_KEY = "/etc/nixfleet-demo/operator.key";
        };

        # First-boot oneshot: sign the CP TLS server cert using the
        # pre-installed fleet CA. The agent's `tls.caCert` is the same
        # CA cert, so the chain validates without out-of-band trust
        # bootstrap. SAN list: `cp` + `cp.demo.invalid` for VLAN peers,
        # 127.0.0.1 + 10.0.100.1 for local probes and the host
        # port-forward (mkVmApps maps 8443 -> guest:8443).
        systemd.services.nixfleet-cp-tls-keygen = {
          description = "First-boot CP TLS server cert (signed by fleet CA)";
          wantedBy = ["multi-user.target"];
          before = ["nixfleet-control-plane.service"];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            User = "root";
            UMask = "0027";
          };
          script = ''
            set -euo pipefail
            tls_dir=/var/lib/nixfleet-control-plane/tls
            mkdir -p "$tls_dir"
            cert="$tls_dir/cert.pem"
            key="$tls_dir/key.pem"
            csr="$tls_dir/cp.csr"
            if [ -f "$cert" ] && [ -f "$key" ]; then
              exit 0
            fi
            ${pkgs.openssl}/bin/openssl genpkey -algorithm ed25519 -out "$key"
            chmod 0600 "$key"
            ${pkgs.openssl}/bin/openssl req -new -key "$key" -out "$csr" \
              -subj "/CN=cp.demo.invalid"
            cat > "$tls_dir/cp.ext" <<EOF
            subjectAltName=DNS:cp,DNS:cp.demo.invalid,DNS:localhost,IP:127.0.0.1,IP:10.0.100.1
            extendedKeyUsage=serverAuth
            EOF
            ${pkgs.openssl}/bin/openssl x509 -req \
              -in "$csr" \
              -CA /etc/nixfleet-demo/fleet-ca.pem \
              -CAkey /etc/nixfleet-demo/fleet-ca-key.pem \
              -CAcreateserial \
              -out "$cert" \
              -days 3650 \
              -extfile "$tls_dir/cp.ext"
            chmod 0644 "$cert"
            rm -f "$csr" "$tls_dir/cp.ext"
          '';
        };

        compliance.frameworks.nis2 = {
          enable = true;
          entityType = "essential";
        };
        compliance.governance.hostType = "server";

        # nixfleet-cli for `nixfleet status` on cp.
        environment.systemPackages = [
          inputs.nixfleet.packages.x86_64-linux.nixfleet-cli
          pkgs.jq
        ];

        nixfleet.persistence.directories = [
          "/var/lib/nixfleet-control-plane"
          "/var/lib/nixfleet-compliance"
        ];
      }
    )
  ];
}
