# Generated by secrets/regenerate-demo-identity.sh -- DO NOT HAND-EDIT.
#
# Operator-declared allowlist of valid bootstrap-token nonces.
# Each entry mirrors the corresponding token's claims.
# CI passes this to nixfleet-release via --bootstrap-nonces-attr.
[
  {
    nonce = "92b9db39a868fec17f906b6a0034682d";
    hostname = "cp";
    expiresAt = "2036-05-16T14:34:04.427227571Z";
    mintedAt = "2026-05-19T14:34:04.427227571Z";
    mintedBy = "regenerate-demo-identity.sh";
  }
  {
    nonce = "3492f9f5cf3ca3595c5cc6307d7acfff";
    hostname = "web-01";
    expiresAt = "2036-05-16T14:34:04.438241259Z";
    mintedAt = "2026-05-19T14:34:04.438241259Z";
    mintedBy = "regenerate-demo-identity.sh";
  }
  {
    nonce = "61d0f1592177455d4b58d9243e8aaa42";
    hostname = "web-02";
    expiresAt = "2036-05-16T14:34:04.449434612Z";
    mintedAt = "2026-05-19T14:34:04.449434612Z";
    mintedBy = "regenerate-demo-identity.sh";
  }
]
