# Demo age recipient. Public -- DO NOT REUSE OUTSIDE THIS DEMO.
# Regenerated by secrets/regenerate-demo-identity.sh.
{
  recipients = [
    "age1802meg45da2h4qm6z7fpnde6apqp82qmhawlcm8tp5t9agzc2pjq8gwfe2"
  ];
}
