# Demo age recipient. Public - DO NOT REUSE OUTSIDE THIS DEMO.
# Regenerated by secrets/regenerate-demo-identity.sh.
{
  recipients = [
    "age15myd2jjn4qsp2uxaa0hvh28pyeun6lpdxknr6ugcxgk9vk3q05vqvst5aq"
  ];
}
