#!/usr/bin/env bash
# Regenerate the demo identity (SSH + age) for nixfleet-demo.
#
# WARNING: All material this script writes is PUBLIC by design.
# The demo ships with checked-in keys so newcomers can boot the
# fleet immediately after `git clone`. Do NOT reuse anything in
# this directory outside the demo.
#
# Run from the repo root: `bash secrets/regenerate-demo-identity.sh`.
# The script is idempotent: if the keys already exist it does nothing
# unless `--force` is passed.

set -euo pipefail

cd "$(dirname "$0")/.."

force=0
if [ "${1:-}" = "--force" ]; then force=1; fi

# --- Step 1: SSH keypair for git@forge ---------------------------------
if [ -f secrets/demo-ssh-key ] && [ "$force" = 0 ]; then
  echo "secrets/demo-ssh-key already exists. Pass --force to regenerate."
else
  rm -f secrets/demo-ssh-key secrets/demo-ssh-key.pub
  ssh-keygen -t ed25519 -N "" \
    -C "nixfleet-demo (PUBLIC, NOT FOR PRODUCTION)" \
    -f secrets/demo-ssh-key
  # Keep the 0600 default ssh-keygen sets — ssh-add and ssh refuse
  # private keys with looser permissions. The key contents are still
  # checked into git (PUBLIC, intentionally), but runtime tools enforce
  # mode independently of the on-disk-vs-tracked distinction.
fi

# --- Step 2: age identity --------------------------------------------------
if [ -f secrets/age-identity.txt ] && [ "$force" = 0 ]; then
  echo "secrets/age-identity.txt already exists. Pass --force to regenerate."
else
  if command -v age-keygen >/dev/null 2>&1; then
    age-keygen -o secrets/age-identity.txt
  else
    echo "ERROR: age-keygen not on PATH. Install rage or age, or run inside a"
    echo "       nix shell that provides them: nix shell nixpkgs#age"
    exit 1
  fi
  # age-identity.txt: leave default 0600. age accepts either; rage
  # warns on looser modes. Same logic as the SSH key above.
fi

# --- Step 3: write secrets/recipients.nix ----------------------------------
# Extract the public key from age-identity.txt.
recipient=$(grep -oE 'age1[a-z0-9]+' secrets/age-identity.txt | head -1)
if [ -z "$recipient" ]; then
  echo "ERROR: could not extract age recipient from secrets/age-identity.txt"
  exit 1
fi

cat >secrets/recipients.nix <<EOF
# Demo age recipient. Public — DO NOT REUSE OUTSIDE THIS DEMO.
# Regenerated by secrets/regenerate-demo-identity.sh.
{
  recipients = [
    "$recipient"
  ];
}
EOF

echo
echo "Demo identity regenerated:"
echo "  - secrets/demo-ssh-key, secrets/demo-ssh-key.pub  (SSH for git@forge)"
echo "  - secrets/age-identity.txt                        (age identity)"
echo "  - secrets/recipients.nix                          (age recipient)"
echo
echo "These files are PUBLIC. Do not deploy this fleet to production."
